Long-term crypto support
open-eid/DigiDoc4-Client pull request #1264
Opened 2024-05-16 09:46 UTC by lauris71

CDOC-13

Tested:
You can encrypt cdoc2 files with symmetric keys (password based and plain keys)
You can decrypt cdoc2 files with symmetric keys
You can encrypt and decrypt cdoc1 and cdoc2 with ID card (as previously)
Not tested:
Key server functionality
Need work:
UI, translations

Signed-off-by: Lauris Kaplinski <lauris@raulwalter.com>

2024-06-03 08:17 UTC, metsma requested changes

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +	return nullptr;
```suggestion
	auto cdoc = std::make_unique<CDoc1>(path);
	if (cdoc->keys.isEmpty())
		cdoc.reset();
	return cdoc;
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +						});
```suggestion
			properties.value(QStringLiteral("Filename")),
			{},
			mime == MIME_ZLIB ? properties.value(QStringLiteral("OriginalMimeType")) : mime,
			properties.value(QStringLiteral("OriginalSize")).toUInt(),
			{}
		});
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +									});
```suggestion
						fileparts.value(0),
						fileparts.value(3),
						fileparts.value(2),
						fileparts.value(1).toUInt(),
						{}
					});
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +	return true;
```suggestion
	
	if(QFile f(path); f.open(QFile::ReadOnly))
		return f.read(XML_TAG.length()) == XML_TAG);
	return false;
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +						});
```suggestion
			properties.value(QStringLiteral("Filename")),
			{},
			mime,
			data.size(),
			std::move(buffer),
		});
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +	if (key) return CKey::DecryptionStatus::CAN_DECRYPT;
```suggestion
	if(getDecryptionKey(cert))
		return CKey::DecryptionStatus::CAN_DECRYPT;
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +					 });
```suggestion
		 {QStringLiteral("Algorithm"), method},
	 });
```

2024-06-03 08:17 UTC, metsma commented on client/CDoc1.cpp
> +									 });
```suggestion
						 {QStringLiteral("Algorithm"), RSA_MTH},
					 });
```

2024-06-17 11:03 UTC, metsma requested changes

2024-06-17 11:03 UTC, metsma commented on client/Crypto.cpp
> +	return QByteArray((const char *) key, 32);
```suggestion
	QByteArray key(32, 0);
	PKCS5_PBKDF2_HMAC(pw.data(), pw.length(),
					  (const unsigned char *) salt.data(), int(salt.length()),
					  iter, EVP_sha256(), int(key.size()), (unsigned char *)key.data());
	return data;
```

2024-06-17 11:03 UTC, metsma commented on client/widgets/ContainerPage.ui
> +          <underline>false</underline>
Changes in this file are not relevant

2024-07-14 21:44 UTC, lauris71 commented on client/Crypto.cpp
> +	return QByteArray((const char *) key, 32);
I think the last line is meant to be 'return key'?

2026-06-04 05:47 UTC, closed without merging

2026-06-04 05:48 UTC, lauris71 commented
Implemented by libcdoc integration

2026-06-04 05:52 UTC, metsma commented
#1329