Fix Linux dark theme
open-eid/DigiDoc4-Client pull request #950
Opened 2021-05-13 11:34 UTC by jsanko

IB-6991
Signed-off-by: Jelena Sanko <jelena@raulwalter.com>

2021-05-13 17:46 UTC, metsma requested changes

2021-05-13 17:46 UTC, metsma commented on client/dialogs/SettingsDialog.ui
> +p, li { white-space: pre-wrap; }
Please revert this change

2021-05-13 18:51 UTC, metsma approved these changes

2021-05-13 18:54 UTC, jsanko commented on client/dialogs/SettingsDialog.ui
> +p, li { white-space: pre-wrap; }
reverted

2021-05-24 08:07 UTC, metsma approved these changes

2021-05-31 08:38 UTC, metsma requested changes

2021-05-31 08:38 UTC, metsma commented on client/dialogs/MobileDialog.ui
>  background-color: #FFFFFF;
You can remove this

2021-05-31 08:38 UTC, metsma commented on client/dialogs/RoleAddressDialog.cpp
> +		completer->popup()->setStyleSheet("background-color:#FFFFFF; color: #000000;");
Can you move this CSS to UI file

2021-05-31 08:38 UTC, metsma commented on client/dialogs/SettingsDialog.cpp
> +#endif
Use one ifdef

2021-05-31 08:38 UTC, metsma commented on client/dialogs/SmartIDDialog.ui
> +     </property>
revert

2021-05-31 12:49 UTC, jsanko commented on client/dialogs/SmartIDDialog.ui
> +     </property>
reverted

2021-05-31 12:51 UTC, jsanko commented on client/dialogs/RoleAddressDialog.cpp
> +		completer->popup()->setStyleSheet("background-color:#FFFFFF; color: #000000;");
moved

2021-05-31 12:51 UTC, jsanko commented on client/dialogs/MobileDialog.ui
>  background-color: #FFFFFF;
removed

2021-06-01 07:31 UTC, metsma approved these changes

2021-07-01 07:37 UTC, metsma approved these changes

2021-07-01 10:46 UTC, merged